DROP DATABASE IF EXISTS classapp_db;
CREATE DATABASE classapp_db;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(20) NOT NULL,
name VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);

SELECT * FROM users;